name: Send Telegram Message on a pull request

on:
  # Triggers the workflow on a pull request event in all branches
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on a pull request
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ✍️ <b>Creator</b>: @${{ github.actor }}
            🔁 <b>Repository</b>: https://github.com/${{ github.repository }}
            <b>PR</b>: ${{ github.ref }}
            <i>Changes</i>: https://github.com/${{ github.repository }}/commit/${{github.sha}}